import fs from 'node:fs';import path from 'node:path';import zlib from 'node:zlib';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';import {decode,encode,readRegion,writeRegion,repack,unpack} from '../fork-world/nbt-region.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const template=process.argv[2];assert(template,'Pass the read-only 26.1.2 template world');
const out=path.join(root,'assets/fork-locator/artifacts/singapore-map-v1');assert(!fs.existsSync(out),'Refuse to overwrite an existing world artifact');
const world=path.join(out,'FORK - Singapore Map'),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),tag=(type,value)=>({type,value}),str=v=>tag(8,v),int=v=>tag(3,v),byte=v=>tag(1,v),compound=v=>tag(10,v),list=(subtype,items)=>tag(9,{subtype,items}),nbt=v=>({type:10,name:'',value:v});
const sourcePath='media/edit/locator-film-v3.svg',sourceBytes=fs.readFileSync(path.join(root,sourcePath)),svg=sourceBytes.toString();assert.equal(sha(sourceBytes.toString().replaceAll('\r\n','\n')),'1278885d5ac330939f9c6e50f2815dc7d422ff1b4db2ef8a4c47e67cb4d21446');
const provenance=JSON.parse(fs.readFileSync(path.join(root,'media/edit/locator-film-v3-provenance.json')));
const d=svg.match(/id="sgp-part-0" d="([^"]+)"/)[1];const pairs=[...d.matchAll(/[ML]([\d.]+),([\d.]+)/g)].map(m=>[+m[1],+m[2]]);
assert.equal(pairs.length,40);
const k=220/1150,transform=([x,y])=>[18+(x-80)*k,128+(y-550)*k],polygon=pairs.map(transform),markerExact=transform([provenance.marker.x,provenance.marker.y]),marker=markerExact.map(Math.round);
function inside(x,z){let yes=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){let a=polygon[i],b=polygon[j];if((a[1]>z)!==(b[1]>z)&&x<(b[0]-a[0])*(z-a[1])/(b[1]-a[1])+a[0])yes=!yes;}return yes;}
const land=new Set();for(let z=0;z<256;z++)for(let x=0;x<256;x++)if(inside(x+.5,z+.5))land.add(x+','+z);
assert(land.has(marker.join(',')));assert(land.has('128,128'));
const palette=['air','blue_concrete','dark_prismarine','prismarine','prismarine_bricks','gold_block'].map(n=>({Name:str('minecraft:'+n)}));
function column(x,z){const on=land.has(x+','+z),edge=on&&[[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dz])=>!land.has((x+dx)+','+(z+dz)));const dx=x-marker[0],dz=z-marker[1],pin=dx*dx+dz*dz<=5;return {on,edge,pin,top:pin?70:on?67:63};}
function block(x,y,z){const c=column(x,z);if(y<62||y>c.top)return 0;if(y<=63)return 1;if(c.pin)return y<68?2:5;if(c.on)return y===67?(c.edge?4:3):2;return 0;}
fs.mkdirSync(path.join(world,'dimensions/minecraft/overworld/region'),{recursive:true});fs.mkdirSync(path.join(world,'data/minecraft'),{recursive:true});
const load=p=>decode(zlib.gunzipSync(fs.readFileSync(path.join(template,p))));const save=(p,r)=>fs.writeFileSync(path.join(world,p),zlib.gzipSync(encode(r)));
const level=load('level.dat'),data=level.value.Data.value;
for(const key of ['singleplayer_uuid','Player','ServerBrands','WasModded'])delete data[key];
data.LevelName=str('FORK - Singapore Map');data.LastPlayed=tag(4,BigInt(Date.now()));data.Time=tag(4,6000n);data.GameType=int(1);data.allowCommands=byte(1);
data.spawn=compound({pos:tag(11,[128,68,128]),pitch:tag(5,0),dimension:str('minecraft:overworld'),yaw:tag(5,0)});data.DataPacks=compound({Enabled:list(8,['vanilla']),Disabled:list(8,[])});save('level.dat',level);
const rules=load('data/minecraft/game_rules.dat');for(const name of ['advance_time','advance_weather','spawn_mobs','spawn_monsters','spawn_phantoms','spawn_patrols','spawn_wandering_traders','raids','send_command_feedback','command_block_output','show_advancement_messages','locator_bar'])rules.value.data.value['minecraft:'+name]=byte(0);rules.value.data.value['minecraft:respawn_radius']=int(0);rules.value.data.value['minecraft:random_tick_speed']=int(0);save('data/minecraft/game_rules.dat',rules);
const weather=load('data/minecraft/weather.dat');weather.value.data.value={rain_time:int(0),raining:byte(0),thundering:byte(0),thunder_time:int(0),clear_weather_time:int(2147483647)};save('data/minecraft/weather.dat',weather);
const clocks=load('data/minecraft/world_clocks.dat');clocks.value.data.value={'minecraft:overworld':compound({total_ticks:tag(4,6000n)})};save('data/minecraft/world_clocks.dat',clocks);
const gen=load('data/minecraft/world_gen_settings.dat'),g=gen.value.data.value;g.seed=tag(4,0n);g.generate_structures=byte(0);
const settings=g.dimensions.value['minecraft:overworld'].value.generator.value.settings.value;settings.biome=str('minecraft:plains');settings.features=byte(0);settings.lakes=byte(0);settings.structure_overrides=list(8,[]);settings.layers=list(10,[{block:str('minecraft:air'),height:int(126)},{block:str('minecraft:blue_concrete'),height:int(2)}]);save('data/minecraft/world_gen_settings.dat',gen);
const regions=new Map(),timestamp=Math.floor(Date.now()/1000);
for(let cz=-8;cz<24;cz++)for(let cx=-8;cx<24;cx++){
 const sections=[];
 for(let sy=-4;sy<20;sy++){const s={Y:byte(sy),biomes:compound({palette:list(8,['minecraft:plains'])}),block_states:compound({palette:list(10,[palette[0]])})};const sky=new Array(2048).fill(sy>4?-1:0);
 if(sy===3||sy===4){const blocks=new Uint16Array(4096);for(let ly=0;ly<16;ly++)for(let lz=0;lz<16;lz++)for(let lx=0;lx<16;lx++){let i=ly*256+lz*16+lx,x=cx*16+lx,z=cz*16+lz,y=sy*16+ly;blocks[i]=block(x,y,z);if(y>column(x,z).top){const idx=i>>1;let u=sky[idx]&255;u|=15<<((i&1)*4);sky[idx]=u>127?u-256:u;}}repack(s,palette,blocks);}s.SkyLight=tag(7,sky);sections.push(s);}
 const heights=new Array(37).fill(0n);for(let z=0;z<16;z++)for(let x=0;x<16;x++){const i=z*16+x,v=column(cx*16+x,cz*16+z).top+65;heights[Math.floor(i/7)]|=BigInt(v)<<BigInt((i%7)*9);}
 const hm=Object.fromEntries(['WORLD_SURFACE','MOTION_BLOCKING','MOTION_BLOCKING_NO_LEAVES','OCEAN_FLOOR'].map(n=>[n,tag(12,heights)]));
 const r=nbt({DataVersion:int(4790),xPos:int(cx),zPos:int(cz),yPos:int(-4),Status:str('minecraft:full'),LastUpdate:tag(4,0n),InhabitedTime:tag(4,0n),isLightOn:byte(1),sections:list(10,sections),Heightmaps:compound(hm),block_entities:list(10,[]),block_ticks:list(10,[]),fluid_ticks:list(10,[]),PostProcessing:list(9,Array.from({length:24},()=>({subtype:2,items:[]}))),structures:compound({starts:compound({}),References:compound({})})});
 const key=Math.floor(cx/32)+'.'+Math.floor(cz/32),chunks=regions.get(key)||[];chunks.push({slot:((cx%32+32)%32)+((cz%32+32)%32)*32,root:r,dirty:true,timestamp});regions.set(key,chunks);
}
for(const [key,chunks]of regions)writeRegion(path.join(world,'dimensions/minecraft/overworld/region/r.'+key+'.mca'),chunks);
// Decode every generated chunk and independently compare every surface column with the source polygon.
let checked=0,pins=0;for(const f of fs.readdirSync(path.join(world,'dimensions/minecraft/overworld/region')))for(const c of readRegion(path.join(world,'dimensions/minecraft/overworld/region',f))){checked++;const v=c.root.value;assert.equal(v.Status.value,'minecraft:full');const s=v.sections.value.items.find(s=>s.Y.value===4),u=unpack(s);for(let z=0;z<16;z++)for(let x=0;x<16;x++){const wx=v.xPos.value*16+x,wz=v.zPos.value*16+z;assert.equal(u.blocks[3*256+z*16+x],block(wx,67,wz));if(u.blocks[6*256+z*16+x]===5)pins++;}}
assert.equal(checked,1024);assert(pins>0);
const camera={position:[128,220,128],yaw:180,pitch:90,verticalFovDegrees:50,aspectRatio:'16:9',north:'screen top; Minecraft -Z',landTopY:67,viewportAtLandBlocks:{width:2*153*Math.tan(25*Math.PI/180)*16/9,height:2*153*Math.tan(25*Math.PI/180)},suggestedRenderDistanceChunks:16,keyframes:[{label:'whole island',position:[128,220,128],yaw:180,pitch:90},{label:'marker push in',position:[marker[0]+.5,110,marker[1]+.5],yaw:180,pitch:90}]};
const manifest={schema:'fork-singapore-map-v1',createdUtc:new Date().toISOString(),purpose:'Actual Minecraft cartographic miniature for cinematic locator transition; separate from gameplay district.',minecraft:{version:'26.1.2',dataVersion:4790,displayName:'FORK - Singapore Map',chunkCount:checked,regionCount:regions.size,oceanBoundsInclusive:[-128,62,-128,383,63,383],mapCanvasBoundsInclusive:[0,0,255,255],landCells:land.size,spawn:[128,68,128],safeFloorY:67,peaceful:true,time:6000,weather:'clear frozen',playersCopied:false},source:{path:sourcePath,sha256:sha(sourceBytes),provenancePath:'media/edit/locator-film-v3-provenance.json',provenanceSha256:sha(fs.readFileSync(path.join(root,'media/edit/locator-film-v3-provenance.json'))),credit:'Made with Natural Earth. Admin 0 v5.1.1, 1:10m, public domain.',url:'https://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-0-countries/',vertexCount:pairs.length,scope:'Generalized main-island only. No offshore islands, invented neighbourhoods, streets or floorplans.'},transform:{svgToMinecraft:{x:'18 + (svgX - 80) * 220/1150',z:'128 + (svgY - 550) * 220/1150'},raster:'Point-in-polygon at block centre, original 40 vertices, no simplification',islandWidthBlocks:220,islandHeightBlocks:(842.028-257.972)*k,approxMetresPerBlock:183.58,claim:'Cartographic miniature, never whole-island 1:1'},marker:{...provenance.marker,meaning:'Market Street district source centre; not a surveyed court coordinate',exactMcXZ:markerExact,blockMcXZ:marker,topY:70,goldCells:pins},camera,validation:{decodedAllChunks:true,surfaceColumnsCompared:checked*256,liveMinecraft:'Pending Laptop load/capture; no native UI used'},files:[]};
function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())walk(p);else{const b=fs.readFileSync(p);manifest.files.push({path:path.relative(world,p).replaceAll('\\','/'),bytes:b.length,sha256:sha(b)});}}}walk(world);manifest.worldBytes=manifest.files.reduce((n,f)=>n+f.bytes,0);
fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');fs.mkdirSync(path.join(root,'data/fork-locator'),{recursive:true});fs.writeFileSync(path.join(root,'data/fork-locator/singapore-map-v1.json'),JSON.stringify({polygon,marker:manifest.marker,transform:manifest.transform,camera},null,2)+'\n');console.log(JSON.stringify({output:out,worldBytes:manifest.worldBytes,chunks:checked,landCells:land.size,marker,camera,manifestSha256:sha(fs.readFileSync(path.join(out,'manifest.json')))}));
