# Gradle runtime
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.16.3
fabric_api_version=0.150.0+26.1.2
carpet_version=26.1+v260402
voicechat_version=2.6.21+26.1.2

# Mod
mod_version=1.0.0-hackathon
maven_group=dev.agaminggod
archives_base_name=fork-minecraft
