import fs from 'node:fs';import {readRegion,sections,unpack,repack,writeRegion} from './nbt-region.mjs';
export class ExpandedWorld{
 constructor(dir){this.dir=dir;this.regions=[];this.chunks=new Map();this.cache=new Map();for(const name of fs.readdirSync(dir+'/region').filter(n=>/^r\.-?\d+\.-?\d+\.mca$/.test(n))){const chunks=readRegion(dir+'/region/'+name);this.regions.push({name,chunks});for(const c of chunks)this.chunks.set([c.root.value.xPos.value,c.root.value.zPos.value].join(','),c);}}
 state(x,y,z){const cx=Math.floor(x/16),cz=Math.floor(z/16),sy=Math.floor(y/16),key=[cx,sy,cz].join(',');let a=this.cache.get(key);if(!a){const c=this.chunks.get([cx,cz].join(','));if(!c)return null;const s=sections(c).find(s=>s.Y.value===sy);if(!s)return null;const v=unpack(s);if(!v)return null;a={...v,s,c,dirty:false};this.cache.set(key,a);}return{a,i:((y%16+16)%16)*256+((z%16+16)%16)*16+(x%16+16)%16};}
 get(x,y,z){const p=this.state(Math.floor(x),Math.floor(y),Math.floor(z));return p?p.a.pal[p.a.blocks[p.i]].Name.value:'minecraft:air';}
 set(x,y,z,name){const p=this.state(x,y,z);if(!p)throw Error('Cannot create absent section');let idx=p.a.pal.findIndex(v=>v.Name.value===name&&!v.Properties);if(idx<0){idx=p.a.pal.length;p.a.pal.push({Name:{type:8,value:name}});}p.a.blocks[p.i]=idx;p.a.dirty=true;p.a.c.dirty=true;}
 heights(size){const tops=new Int16Array(size*size).fill(-32768);for(const c of this.chunks.values()){const cx=c.root.value.xPos.value*16,cz=c.root.value.zPos.value*16;if(cx<0||cz<0||cx>=size||cz>=size)continue;const found=new Uint8Array(256);let remaining=256;for(const s of [...sections(c)].sort((a,b)=>b.Y.value-a.Y.value)){const a=unpack(s);if(!a||a.pal.every(p=>/:(air|cave_air|void_air)$/.test(p.Name.value)))continue;for(let y=15;y>=0&&remaining;y--)for(let i=0;i<256;i++){if(found[i])continue;const n=a.pal[a.blocks[y*256+i]].Name.value;if(!/:(air|cave_air|void_air)$/.test(n)){tops[(cz+Math.floor(i/16))*size+cx+i%16]=s.Y.value*16+y;found[i]=1;remaining--;}}if(!remaining)break;}}return tops;}
 save(){for(const a of this.cache.values())if(a.dirty){repack(a.s,a.pal,a.blocks);a.c.root.value.isLightOn={type:1,value:0};for(const s of sections(a.c)){delete s.BlockLight;delete s.SkyLight;}}for(const r of this.regions)if(r.chunks.some(c=>c.dirty))writeRegion(this.dir+'/region/'+r.name,r.chunks);}
}
