import fs from 'node:fs';import path from 'node:path';import zlib from 'node:zlib';import crypto from 'node:crypto';
const dir='assets/fork-world/artifacts/compact-1121/world-output/Arnis World 1';
function nbt(b){let p=0;const u8=()=>b.readUInt8(p++),str=()=>{let n=b.readUInt16BE(p);p+=2;let s=b.toString('utf8',p,p+n);p+=n;return s;};function v(t){let n,r;switch(t){case 1:r=b.readInt8(p);p++;return r;case 2:r=b.readInt16BE(p);p+=2;return r;case 3:r=b.readInt32BE(p);p+=4;return r;case 4:r=b.readBigInt64BE(p);p+=8;return r;case 5:r=b.readFloatBE(p);p+=4;return r;case 6:r=b.readDoubleBE(p);p+=8;return r;case 7:n=b.readInt32BE(p);p+=4;r=b.subarray(p,p+n);p+=n;return r;case 8:return str();case 9:{const kind=u8();n=b.readInt32BE(p);p+=4;r=[];for(let i=0;i<n;i++)r.push(v(kind));return r;}case 10:r={};while((n=u8())!==0){const key=str();r[key]=v(n);}return r;case 11:n=b.readInt32BE(p);p+=4;r=[];for(let i=0;i<n;i++){r.push(b.readInt32BE(p));p+=4;}return r;case 12:n=b.readInt32BE(p);p+=4;r=[];for(let i=0;i<n;i++){r.push(b.readBigUInt64BE(p));p+=8;}return r;default:throw Error('NBT type '+t);}}const t=u8();str();return v(t);}
const level=nbt(zlib.gunzipSync(fs.readFileSync(path.join(dir,'level.dat')))).Data;
const b=fs.readFileSync(path.join(dir,'region/r.0.0.mca')),palettes=new Set(),versions=new Set(),chunks=[];let highest=-Infinity,lowest=Infinity,solidBlocks=0;
for(let i=0;i<1024;i++){const loc=b.readUInt32BE(i*4),sector=loc>>>8;if(!sector)continue;const off=sector*4096,len=b.readUInt32BE(off),type=b[off+4],compressed=b.subarray(off+5,off+4+len);if(type!==2)throw Error('Unexpected compression '+type);const c=nbt(zlib.inflateSync(compressed));versions.add(c.DataVersion);chunks.push([c.xPos,c.zPos]);for(const s of c.sections??[]){const bs=s.block_states;if(!bs?.palette)continue;const pal=bs.palette.map(x=>x.Name);pal.forEach(x=>palettes.add(x));const air=pal.map(x=>x==='minecraft:air'||x==='minecraft:cave_air'||x==='minecraft:void_air');if(air.every(Boolean))continue;const bits=Math.max(4,Math.ceil(Math.log2(pal.length))),perLong=Math.floor(64/bits),mask=(1n<<BigInt(bits))-1n;for(let j=0;j<4096;j++){const idx=pal.length===1?0:Number((bs.data[Math.floor(j/perLong)]>>BigInt((j%perLong)*bits))&mask);if(idx>=pal.length)throw Error('Bad palette index');if(!air[idx]){const y=s.Y*16+Math.floor(j/256);highest=Math.max(highest,y);lowest=Math.min(lowest,y);solidBlocks++;}}}}
const files=[];function scan(p){for(const e of fs.readdirSync(p,{withFileTypes:true})){const q=path.join(p,e.name);if(e.isDirectory())scan(q);else{const data=fs.readFileSync(q);files.push({path:q.replaceAll('\\','/'),bytes:data.length,sha256:crypto.createHash('sha256').update(data).digest('hex')});}}}scan(dir);
const out={status:'STRUCTURAL READ ONLY; no game reopen or placement accepted',levelDataVersion:level.DataVersion,levelName:level.LevelName,spawn:[level.SpawnX,level.SpawnY,level.SpawnZ],chunkDataVersions:[...versions],chunks:chunks.length,chunkBounds:[Math.min(...chunks.map(x=>x[0])),Math.min(...chunks.map(x=>x[1])),Math.max(...chunks.map(x=>x[0])),Math.max(...chunks.map(x=>x[1]))],lowestNonAirY:lowest,highestNonAirY:highest,solidBlocks,palette:[...palettes].sort(),bytes:files.reduce((n,f)=>n+f.bytes,0),files};fs.writeFileSync('.work/fork/world/cache/world-structure.json',JSON.stringify(out,null,2));console.log(JSON.stringify({...out,files:undefined,palette:undefined,paletteCount:palettes.size}));

