import fs from 'node:fs';
import zlib from 'node:zlib';
export function decode(b){let p=0;const byte=()=>b[p++],s=()=>{let n=b.readUInt16BE(p);p+=2;const v=b.toString('utf8',p,p+n);p+=n;return v;};
 function val(t){let n,v;switch(t){case 1:v=b.readInt8(p);p++;break;case 2:v=b.readInt16BE(p);p+=2;break;case 3:v=b.readInt32BE(p);p+=4;break;case 4:v=b.readBigInt64BE(p);p+=8;break;case 5:v=b.readFloatBE(p);p+=4;break;case 6:v=b.readDoubleBE(p);p+=8;break;case 8:v=s();break;case 7:case 11:case 12:n=b.readInt32BE(p);p+=4;v=[];for(let i=0;i<n;i++)v.push(val(t===7?1:t===11?3:4));break;case 9:{const subtype=byte();n=b.readInt32BE(p);p+=4;v={subtype,items:[]};for(let i=0;i<n;i++)v.items.push(val(subtype));break;}case 10:v={};while((n=byte())!==0){const name=s();v[name]={type:n,value:val(n)};}break;default:throw Error('Unsupported NBT '+t);}return v;}
 const type=byte(),name=s(),value=val(type);if(p!==b.length)throw Error('Trailing NBT');return {type,name,value};}
export function encode(root){const parts=[],push=b=>parts.push(b);function num(t,v){let b=Buffer.alloc({1:1,2:2,3:4,4:8,5:4,6:8}[t]);({1:()=>b.writeInt8(v),2:()=>b.writeInt16BE(v),3:()=>b.writeInt32BE(v),4:()=>b.writeBigInt64BE(BigInt.asIntN(64,v)),5:()=>b.writeFloatBE(v),6:()=>b.writeDoubleBE(v)})[t]();push(b);}function str(v){const b=Buffer.from(v);const n=Buffer.alloc(2);n.writeUInt16BE(b.length);push(n);push(b);}function val(t,v){if(t<=6){num(t,v);return;}switch(t){case 8:str(v);break;case 7:case 11:case 12:num(3,v.length);for(const x of v)val(t===7?1:t===11?3:4,x);break;case 9:num(1,v.subtype);num(3,v.items.length);for(const x of v.items)val(v.subtype,x);break;case 10:for(const [k,x] of Object.entries(v)){num(1,x.type);str(k);val(x.type,x.value);}num(1,0);break;default:throw Error('Unsupported NBT '+t);}}
 num(1,root.type);str(root.name);val(root.type,root.value);return Buffer.concat(parts);}
export function readRegion(p){const b=fs.readFileSync(p),chunks=[];for(let i=0;i<1024;i++){const sector=b.readUInt32BE(i*4)>>>8;if(!sector)continue;const off=sector*4096,len=b.readUInt32BE(off);if(b[off+4]!==2)throw Error('Only zlib chunks supported');const packed=b.subarray(off+5,off+4+len);chunks.push({slot:i,packed,root:decode(zlib.inflateSync(packed)),dirty:false,timestamp:b.readUInt32BE(4096+i*4)});}return chunks;}
export function writeRegion(p,chunks){const head=Buffer.alloc(8192),body=[];let sector=2;for(const c of chunks){const packed=c.dirty?zlib.deflateSync(encode(c.root)):c.packed,n=Math.ceil((packed.length+5)/4096),b=Buffer.alloc(n*4096);if(n>255)throw Error('Chunk too large');b.writeUInt32BE(packed.length+1);b[4]=2;packed.copy(b,5);head.writeUInt32BE((sector<<8)|n,c.slot*4);head.writeUInt32BE(c.timestamp,4096+c.slot*4);body.push(b);sector+=n;}fs.writeFileSync(p,Buffer.concat([head,...body]));}
export function sections(c){return c.root.value.sections.value.items;}
export function unpack(s){const bs=s.block_states?.value;if(!bs)return null;const pal=bs.palette.value.items;const data=bs.data?.value;const bits=Math.max(4,Math.ceil(Math.log2(pal.length))),per=Math.floor(64/bits),mask=(1n<<BigInt(bits))-1n;const blocks=new Uint16Array(4096);if(pal.length>1)for(let i=0;i<4096;i++)blocks[i]=Number((BigInt.asUintN(64,data[Math.floor(i/per)])>>BigInt(i%per*bits))&mask);return {pal,blocks};}
export function repack(s,pal,blocks){const bits=Math.max(4,Math.ceil(Math.log2(pal.length))),per=Math.floor(64/bits),data=new Array(Math.ceil(4096/per)).fill(0n);for(let i=0;i<4096;i++)data[Math.floor(i/per)]|=BigInt(blocks[i])<<BigInt(i%per*bits);s.block_states.value={palette:{type:9,value:{subtype:10,items:pal}},data:{type:12,value:data.map(v=>BigInt.asIntN(64,v))}};}
