import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const privateDir=path.join(root,'.work/fork/world/cache-ground0');
const artifactDir=path.join(root,'assets/fork-world/artifacts/compact-ground0');
const source=path.join(root,'assets/fork-world/artifacts/compact-1121/render-complete.json');
const deadline=Date.parse('2026-09-13T03:36:50Z');
if(Date.now()>=deadline-30000)throw new Error('Insufficient time before absolute generation stop.');
if(process.argv[2]!=='native-cache-lease-confirmed')throw new Error('Main must explicitly authorize native Arnis cache paths before launch.');
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
if(hash(source)!=='e89ce3c667afff96921f243530918123dcf146bbe962568d842ae1e92992317c')throw new Error('Input hash mismatch');
const exe=path.join(process.env.LOCALAPPDATA,'FORK-Tools/arnis-3.2.0/arnis.exe');
if(hash(exe)!=='79ccb74c9c0af38b025a24678d301cb4f7036dd49784e8d35bb0d5b4c15a32d6')throw new Error('Arnis executable hash mismatch');
const out=path.join(artifactDir,'world-output');
if(fs.existsSync(out))throw new Error('Fresh output only; no append/retry.');
fs.mkdirSync(out);
const args=['--body','earth','--mode','geo-only','--projection','local','--scale','1','--rotation','0','--ground-level','0','--overture','false','--canopy-height','false','--no-3d','--legacy-trees','--mapillary-facades','false','--signage','none','--map-item','false','--interior','false','--world-time','6000','--bbox','1.281850162,103.848849873,1.284149838,103.851150127','--file',source,'--output-dir',out];
const settings={executableSha256:hash(exe),args,sourceSha256:hash(source),deadlineUtc:new Date(deadline).toISOString(),threads:4};
fs.writeFileSync(path.join(artifactDir,'run-settings.json'),JSON.stringify(settings,null,2));
const log=fs.openSync(path.join(privateDir,'arnis-stdout.log'),'wx'),err=fs.openSync(path.join(privateDir,'arnis-stderr.log'),'wx');
const started=Date.now(),child=spawn(exe,args,{cwd:privateDir,windowsHide:true,stdio:['ignore',log,err],env:{...process.env,RAYON_NUM_THREADS:'4'}});
const record={job:'compact-ground0',pid:child.pid??null,startedUtc:new Date(started).toISOString(),settingsSha256:hash(path.join(artifactDir,'run-settings.json')),sourceSha256:settings.sourceSha256,outputPath:'assets/fork-world/artifacts/compact-ground0/world-output',cachePolicy:'Native caches require explicit Main lease; temporary files in owned cache.',stopUtc:settings.deadlineUtc,exitUtc:null,exitCode:null,timedOut:false,writerStopped:false};
const recordPath=path.join(privateDir,'job.json'),save=()=>fs.writeFileSync(recordPath,JSON.stringify(record,null,2));save();console.log(JSON.stringify(record));
const timer=setTimeout(()=>{if(child.exitCode===null){record.timedOut=true;save();const killer=spawn('C:/Windows/System32/taskkill.exe',['/PID',String(child.pid),'/T','/F'],{windowsHide:true,stdio:'ignore'});killer.on('error',e=>{record.stopError=e.message;save();});}},Math.max(0,deadline-Date.now()));
child.on('error',e=>{record.launchError=e.message;save();});
child.on('close',(code,signal)=>{clearTimeout(timer);fs.closeSync(log);fs.closeSync(err);record.exitUtc=new Date().toISOString();record.elapsedSeconds=(Date.now()-started)/1000;record.exitCode=code;record.signal=signal;record.writerStopped=true;record.outputChildren=fs.readdirSync(out);save();console.log(JSON.stringify(record));process.exitCode=code===0&&!record.timedOut?0:1;});

