import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const read=p=>JSON.parse(fs.readFileSync(p)),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const base='data/fork-world/locator/',u=read(base+'upstream-record.json'),m=read(base+'source-manifest.json'),original=read(base+'source-feature.geojson').features[0],derived=read(base+'singapore-ne-5.1.1.geojson').features[0],svg=fs.readFileSync('assets/fork-world/locator/singapore-locator.svg','utf8');
assert.equal(u.gitBlobSha1,'5ebc66e25fc1af01edaebe9375c546655e04cf1e');assert.equal(u.sha256,'239eec57ac17f100a11e2536cffc56752c318b50ae765b0918ff7aab4ce8f255');assert.equal(hash(base+'source-feature.geojson'),u.subsetSha256);assert.equal(m.source.sha256,u.sha256);assert.equal(m.source.selectedInputSha256,u.subsetSha256);
assert.equal(original.properties.ADM0_A3,'SGP');assert.deepEqual(derived.geometry,original.geometry);assert.equal(derived.geometry.type,'Polygon');assert.equal(derived.geometry.coordinates.length,1);assert.equal(derived.geometry.coordinates[0].length,40);
assert.deepEqual(m.coordinates.bboxLngLat,[103.640391,1.264309,104.003429,1.448635]);assert.deepEqual(m.coordinates.axisOrder,['longitude_deg','latitude_deg']);assert.equal(m.coordinates.crs,'OGC:CRS84');
const proj=m.coordinates.svgProject,ring=derived.geometry.coordinates[0],commands=[...svg.matchAll(/[ML]([\d.]+),([\d.]+)/g)].map(v=>[+v[1],+v[2]]);assert.equal(commands.length,ring.length);
for(let i=0;i<ring.length;i++){const [lng,lat]=ring[i],[x,y]=commands[i];const recoveredLng=(x-proj.x0)/(proj.scalePixelsPerDegreeLatitude*proj.longitudeCosine)+proj.westLongitude,recoveredLat=proj.northLatitude-(y-proj.y0)/proj.scalePixelsPerDegreeLatitude;assert(Math.abs(lng-recoveredLng)<0.0000002);assert(Math.abs(lat-recoveredLat)<0.0000002);assert(x>=79.999&&x<=1230.001&&y>=254.999&&y<=845.001);}
for(const o of m.outputs)assert.equal(hash(o.path),o.sha256);
assert.equal(m.coverage.playable.geographicCourtAnchor,null);assert.equal(m.coverage.playable.courtMapMarker,false);assert.equal(m.coverage.playable.livePlacementAccepted,false);assert(!svg.includes('<circle'));assert(svg.includes('Fictional court'));assert(svg.includes('Offshore islands are not depicted'));assert(svg.includes('Made with Natural Earth'));assert(svg.includes('width="1920" height="1080"'));
assert.equal(hash('data/fork-world/court-v1.json'),'538149df807a946101e7f8a14806aa3464b874ad4b3ae626451291ca2f3d9e14');
console.log('PASS upstream pins, exact geometry preservation (40 vertices), all projected coordinates/inverse transform, bounds/CRS, output hashes, attribution, no geographic court marker, accepted court unchanged.');
