import assert from 'node:assert/strict';
import path from 'node:path';
import {queueLease,sourceQuarantine} from './pipeline-job-policy.mjs';
const policy={approvedBy:'/root/singapore_full_coordinator',heavyJobSlot:'A',cpuThreads:1,memoryGiB:4,expiresUtc:'2026-09-13T11:50:00Z'};
const id='a'.repeat(64),root=path.resolve('fixture/queue/jobs/'+id+'/attempt-1/output'),env={FORK_JOB_ID:id,FORK_JOB_ATTEMPT:'1',FORK_OUTPUT_DIR:root},now=new Date('2026-09-13T09:00:00Z');
assert.equal(queueLease(policy,root,env,now).outputRoot,root);
assert.throws(()=>queueLease(policy,root,{...env,FORK_JOB_ATTEMPT:'2'},now));
assert.throws(()=>queueLease({...policy,memoryGiB:8},root,env,now));
assert.throws(()=>queueLease(policy,root,env,new Date('2026-09-13T12:00:00Z')));
const features=[{id:'way/1',properties:{tags:{'building:part':'yes',height:'280',min_height:'282'}}}];
const q={mode:'invalid-building-parts-report',approvedBy:policy.approvedBy,maxFraction:0.1};
const manifest={selectedFeatureCount:9,exclusions:[{featureId:'way/1',reason:'min_height 282 exceeds height280'}],completeSourceGeometryAccepted:false};
const report=sourceQuarantine(manifest,features,q);assert.equal(report.excludedFraction,.1);assert.equal(report.exclusions[0].originalTags.min_height,'282');assert.equal(report.sourceGeometryComplete,false);
assert.throws(()=>sourceQuarantine({...manifest,selectedFeatureCount:8},features,q));
assert.throws(()=>sourceQuarantine({...manifest,exclusions:[{featureId:'way/1',reason:'missing polygon coordinates'}]},features,q));
assert.throws(()=>sourceQuarantine(manifest,[{id:'way/1',properties:{tags:{building:'yes'}}}],q));
assert.throws(()=>sourceQuarantine(manifest,features,undefined));
assert.equal(sourceQuarantine(manifest,features,undefined,['1']).excludedCount,1);
console.log('PASS queue attempt identity/resource binding and bounded explicit source quarantine');
